version : 3

tasks:
  build:
    cmds:
      - go build -o bin/app cmd/main.go
  run:
    cmds:
      - task build
      - ./bin/app
  proto:
    cmds:
      - protoc --go_out=. --go-grpc_out=. pkg/proto/auth.proto
  deps:
    cmds:
      - go mod download